lithops: 
    storage: redis
    backend: openwhisk

openwhisk:
    endpoint    : http://192.168.6.1:31001
    namespace   : guest
    api_key     : 23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP
    insecure    : True

redis:
    host: <TODO>
    port: 6379
    password: password
