
adminUsername: admin

# super insecure
adminPassword: password
#affinity:
#  nodeAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      nodeSelectorTerms:
#      - matchExpressions:
#        - key: openwhisk
#          operator: In
#          values:
#          - core   
